### ISSUE TITLE
Web sample is not working on build

### ISSUE THREAD

**Issue by classicalguss** [AgoraIO/Agora-Chat-API-Examples#83]
When running npm run build. I get the following error.

node:internal/crypto/hash:80
  this[kHandle] = new _Hash(algorithm, xofLen, algorithmId, getHashCache());
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:80:19)
    at Object.createHash (node:crypto:139:10)
    at BulkUpdateDecorator.hashFactory (/Users/ghassanbarghouti/Documents/Agora-Chat-API-Examples/Chat-Web/node_modules/webpack/lib/util/createHash.js:155:18)
    at BulkUpdateDecorator.update (/Users/ghassanbarghouti/Documents/Agora-Chat-API-Examples/Chat-Web/node_modules/webpack/lib/util/createHash.js:46:50)
    at RawSource.updateHash (/Users/ghassanbarghouti/Documents/Agora-Chat-API-Examples/Chat-Web/node_modules/webpack-sources/lib/RawSource.js:77:8)
    at NormalModule._initBuildHash (/Users/ghassanbarghouti/Documents/Agora-Chat-API-Examples/Chat-Web/node_modules/webpack/lib/NormalModule.js:888:17)
    at handleParseResult (/Users/ghassanbarghouti/Documents/Agora-Chat-API-Examples/Chat-Web/node_modules/webpack/lib/NormalModule.js:954:10)
    at /Users/ghassanbarghouti/Documents/Agora-Chat-API-Examples/Chat-Web/node_modules/webpack/lib/NormalModule.js:1048:4
    at processResult (/Users/ghassanbarghouti/Documents/Agora-Chat-API-Examples/Chat-Web/node_modules/webpack/lib/NormalModule.js:763:11)
    at /Users/ghassanbarghouti/Documents/Agora-Chat-API-Examples/Chat-Web/node_modules/webpack/lib/NormalModule.js:827:5 {
  opensslErrorStack: [
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v21.7.1

**Comment by myZhangDong** [comment]
This issue is due to the use of different versions of the OpenSSL library after node 17， You can refer to this solution to solve this problem https://github.com/webpack/webpack/issues/14532.  export NODE_OPTIONS=--openssl-legacy-provider
